-- MySQL Script generated by MySQL Workbench
-- Fri Oct 23 13:32:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `iduser_UNIQUE` (`idUser` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`list` (
  `idList` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `user_idUserAdmin` INT(11) NOT NULL,
  PRIMARY KEY (`idList`),
  UNIQUE INDEX `idgrouplist_UNIQUE` (`idList` ASC) ,
  INDEX `fk_list_user1_idx` (`user_idUserAdmin` ASC) ,
  CONSTRAINT `fk_list_user1`
    FOREIGN KEY (`user_idUserAdmin`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `idTask` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `date` DATETIME NOT NULL,
  `complete` TINYINT(4) NOT NULL,
  `list_idList` INT(11) NOT NULL,
  PRIMARY KEY (`idTask`),
  UNIQUE INDEX `idlist_UNIQUE` (`idTask` ASC) ,
  INDEX `fk_task_list1_idx` (`list_idList` ASC) ,
  CONSTRAINT `idlist`
    FOREIGN KEY (`list_idList`)
    REFERENCES `mydb`.`list` (`idList`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`user_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_list` (
  `user_idUser` INT(11) NOT NULL,
  `list_idList` INT(11) NOT NULL,
  PRIMARY KEY (`user_idUser`, `list_idList`),
  INDEX `fk_user_has_grouplist1_grouplist1_idx` (`list_idList` ASC) ,
  INDEX `fk_user_has_grouplist1_user1_idx` (`user_idUser` ASC) ,
  CONSTRAINT `fk_user_has_grouplist1_grouplist1`
    FOREIGN KEY (`list_idList`)
    REFERENCES `mydb`.`list` (`idList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_grouplist1_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
